name: Schedule Updater Auto-Bot

on:
  schedule:
    - cron: '0 */6 * * *' 
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run Scraper
        run: node js/schedule_scraper.js
        env:
          SECRET_DATA_URL: ${{ secrets.SECRET_DATA_URL }}

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add js/schedule_data.json
          git commit -m "Auto update js/schedule_data.json" || exit 0
          git push
