name: Chart Updater Auto-Bot

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: import
        uses: actions/checkout@v3

      - name: settings
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: install
        run: npm install

      - name: start
        run: node scripts/scrape_chart.js

      - name: save
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add chart/chart_data.json
          git commit -m "Auto update chart/chart_data.json" || exit 0
          git push
